//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 10/19/2015 4:12:25 PM
namespace Example.Tests.Client.Example.Data.Models
{
    /// <summary>
    /// There are no comments for RaceSingle in the schema.
    /// </summary>
    public partial class RaceSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Race>
    {
        /// <summary>
        /// Initialize a new RaceSingle object.
        /// </summary>
        public RaceSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new RaceSingle object.
        /// </summary>
        public RaceSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new RaceSingle object.
        /// </summary>
        public RaceSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Race> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for Race in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    public partial class Race : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Race object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="laps">Initial value of Laps.</param>
        /// <param name="startDateTime">Initial value of StartDateTime.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static Race CreateRace(int ID, int laps, global::System.DateTimeOffset startDateTime)
        {
            Race race = new Race();
            race.Id = ID;
            race.Laps = laps;
            race.StartDateTime = startDateTime;
            return race;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Laps in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public int Laps
        {
            get
            {
                return this._Laps;
            }
            set
            {
                this.OnLapsChanging(value);
                this._Laps = value;
                this.OnLapsChanged();
                this.OnPropertyChanged("Laps");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _Laps;
        partial void OnLapsChanging(int value);
        partial void OnLapsChanged();
        /// <summary>
        /// There are no comments for Property StartDateTime in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::System.DateTimeOffset StartDateTime
        {
            get
            {
                return this._StartDateTime;
            }
            set
            {
                this.OnStartDateTimeChanging(value);
                this._StartDateTime = value;
                this.OnStartDateTimeChanged();
                this.OnPropertyChanged("StartDateTime");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.DateTimeOffset _StartDateTime;
        partial void OnStartDateTimeChanging(global::System.DateTimeOffset value);
        partial void OnStartDateTimeChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for DriverSingle in the schema.
    /// </summary>
    public partial class DriverSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Driver>
    {
        /// <summary>
        /// Initialize a new DriverSingle object.
        /// </summary>
        public DriverSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new DriverSingle object.
        /// </summary>
        public DriverSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new DriverSingle object.
        /// </summary>
        public DriverSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Driver> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Cars in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::Example.Tests.Client.Example.Data.Models.Car> Cars
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Cars == null))
                {
                    this._Cars = Context.CreateQuery<global::Example.Tests.Client.Example.Data.Models.Car>(GetPath("Cars"));
                }
                return this._Cars;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Example.Tests.Client.Example.Data.Models.Car> _Cars;
    }
    /// <summary>
    /// There are no comments for Driver in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    public partial class Driver : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Driver object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static Driver CreateDriver(int ID)
        {
            Driver driver = new Driver();
            driver.Id = ID;
            return driver;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Cars in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceCollection<global::Example.Tests.Client.Example.Data.Models.Car> Cars
        {
            get
            {
                return this._Cars;
            }
            set
            {
                this.OnCarsChanging(value);
                this._Cars = value;
                this.OnCarsChanged();
                this.OnPropertyChanged("Cars");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::Example.Tests.Client.Example.Data.Models.Car> _Cars = new global::Microsoft.OData.Client.DataServiceCollection<global::Example.Tests.Client.Example.Data.Models.Car>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnCarsChanging(global::Microsoft.OData.Client.DataServiceCollection<global::Example.Tests.Client.Example.Data.Models.Car> value);
        partial void OnCarsChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for CarSingle in the schema.
    /// </summary>
    public partial class CarSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Car>
    {
        /// <summary>
        /// Initialize a new CarSingle object.
        /// </summary>
        public CarSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new CarSingle object.
        /// </summary>
        public CarSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new CarSingle object.
        /// </summary>
        public CarSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Car> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Owner in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Example.Tests.Client.Example.Data.Models.DriverSingle Owner
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Owner == null))
                {
                    this._Owner = new global::Example.Tests.Client.Example.Data.Models.DriverSingle(this.Context, GetPath("Owner"));
                }
                return this._Owner;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Example.Tests.Client.Example.Data.Models.DriverSingle _Owner;
    }
    /// <summary>
    /// There are no comments for Car in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    public partial class Car : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Car object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="year">Initial value of Year.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static Car CreateCar(int ID, int year)
        {
            Car car = new Car();
            car.Id = ID;
            car.Year = year;
            return car;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Year in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public int Year
        {
            get
            {
                return this._Year;
            }
            set
            {
                this.OnYearChanging(value);
                this._Year = value;
                this.OnYearChanged();
                this.OnPropertyChanged("Year");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _Year;
        partial void OnYearChanging(int value);
        partial void OnYearChanged();
        /// <summary>
        /// There are no comments for Property Make in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string Make
        {
            get
            {
                return this._Make;
            }
            set
            {
                this.OnMakeChanging(value);
                this._Make = value;
                this.OnMakeChanged();
                this.OnPropertyChanged("Make");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Make;
        partial void OnMakeChanging(string value);
        partial void OnMakeChanged();
        /// <summary>
        /// There are no comments for Property Model in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string Model
        {
            get
            {
                return this._Model;
            }
            set
            {
                this.OnModelChanging(value);
                this._Model = value;
                this.OnModelChanged();
                this.OnPropertyChanged("Model");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Model;
        partial void OnModelChanging(string value);
        partial void OnModelChanged();
        /// <summary>
        /// There are no comments for Property Owner in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Example.Tests.Client.Example.Data.Models.Driver Owner
        {
            get
            {
                return this._Owner;
            }
            set
            {
                this.OnOwnerChanging(value);
                this._Owner = value;
                this.OnOwnerChanged();
                this.OnPropertyChanged("Owner");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Example.Tests.Client.Example.Data.Models.Driver _Owner;
        partial void OnOwnerChanging(global::Example.Tests.Client.Example.Data.Models.Driver value);
        partial void OnOwnerChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for RaceResultSingle in the schema.
    /// </summary>
    public partial class RaceResultSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<RaceResult>
    {
        /// <summary>
        /// Initialize a new RaceResultSingle object.
        /// </summary>
        public RaceResultSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new RaceResultSingle object.
        /// </summary>
        public RaceResultSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new RaceResultSingle object.
        /// </summary>
        public RaceResultSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<RaceResult> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Race in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Example.Tests.Client.Example.Data.Models.RaceSingle Race
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Race == null))
                {
                    this._Race = new global::Example.Tests.Client.Example.Data.Models.RaceSingle(this.Context, GetPath("Race"));
                }
                return this._Race;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Example.Tests.Client.Example.Data.Models.RaceSingle _Race;
        /// <summary>
        /// There are no comments for Car in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Example.Tests.Client.Example.Data.Models.CarSingle Car
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Car == null))
                {
                    this._Car = new global::Example.Tests.Client.Example.Data.Models.CarSingle(this.Context, GetPath("Car"));
                }
                return this._Car;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Example.Tests.Client.Example.Data.Models.CarSingle _Car;
        /// <summary>
        /// There are no comments for Driver in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Example.Tests.Client.Example.Data.Models.DriverSingle Driver
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Driver == null))
                {
                    this._Driver = new global::Example.Tests.Client.Example.Data.Models.DriverSingle(this.Context, GetPath("Driver"));
                }
                return this._Driver;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Example.Tests.Client.Example.Data.Models.DriverSingle _Driver;
    }
    /// <summary>
    /// There are no comments for RaceResult in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    public partial class RaceResult : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new RaceResult object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="didFinish">Initial value of DidFinish.</param>
        /// <param name="didStart">Initial value of DidStart.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static RaceResult CreateRaceResult(int ID, bool didFinish, bool didStart)
        {
            RaceResult raceResult = new RaceResult();
            raceResult.Id = ID;
            raceResult.DidFinish = didFinish;
            raceResult.DidStart = didStart;
            return raceResult;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property FinishTimeSpan in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::System.Nullable<global::System.TimeSpan> FinishTimeSpan
        {
            get
            {
                return this._FinishTimeSpan;
            }
            set
            {
                this.OnFinishTimeSpanChanging(value);
                this._FinishTimeSpan = value;
                this.OnFinishTimeSpanChanged();
                this.OnPropertyChanged("FinishTimeSpan");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<global::System.TimeSpan> _FinishTimeSpan;
        partial void OnFinishTimeSpanChanging(global::System.Nullable<global::System.TimeSpan> value);
        partial void OnFinishTimeSpanChanged();
        /// <summary>
        /// There are no comments for Property DidFinish in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public bool DidFinish
        {
            get
            {
                return this._DidFinish;
            }
            set
            {
                this.OnDidFinishChanging(value);
                this._DidFinish = value;
                this.OnDidFinishChanged();
                this.OnPropertyChanged("DidFinish");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private bool _DidFinish;
        partial void OnDidFinishChanging(bool value);
        partial void OnDidFinishChanged();
        /// <summary>
        /// There are no comments for Property DidStart in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public bool DidStart
        {
            get
            {
                return this._DidStart;
            }
            set
            {
                this.OnDidStartChanging(value);
                this._DidStart = value;
                this.OnDidStartChanged();
                this.OnPropertyChanged("DidStart");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private bool _DidStart;
        partial void OnDidStartChanging(bool value);
        partial void OnDidStartChanged();
        /// <summary>
        /// There are no comments for Property LapsCompleted in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::System.Nullable<int> LapsCompleted
        {
            get
            {
                return this._LapsCompleted;
            }
            set
            {
                this.OnLapsCompletedChanging(value);
                this._LapsCompleted = value;
                this.OnLapsCompletedChanged();
                this.OnPropertyChanged("LapsCompleted");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<int> _LapsCompleted;
        partial void OnLapsCompletedChanging(global::System.Nullable<int> value);
        partial void OnLapsCompletedChanged();
        /// <summary>
        /// There are no comments for Property PitStops in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::System.Nullable<int> PitStops
        {
            get
            {
                return this._PitStops;
            }
            set
            {
                this.OnPitStopsChanging(value);
                this._PitStops = value;
                this.OnPitStopsChanged();
                this.OnPropertyChanged("PitStops");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<int> _PitStops;
        partial void OnPitStopsChanging(global::System.Nullable<int> value);
        partial void OnPitStopsChanged();
        /// <summary>
        /// There are no comments for Property Race in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Example.Tests.Client.Example.Data.Models.Race Race
        {
            get
            {
                return this._Race;
            }
            set
            {
                this.OnRaceChanging(value);
                this._Race = value;
                this.OnRaceChanged();
                this.OnPropertyChanged("Race");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Example.Tests.Client.Example.Data.Models.Race _Race;
        partial void OnRaceChanging(global::Example.Tests.Client.Example.Data.Models.Race value);
        partial void OnRaceChanged();
        /// <summary>
        /// There are no comments for Property Car in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Example.Tests.Client.Example.Data.Models.Car Car
        {
            get
            {
                return this._Car;
            }
            set
            {
                this.OnCarChanging(value);
                this._Car = value;
                this.OnCarChanged();
                this.OnPropertyChanged("Car");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Example.Tests.Client.Example.Data.Models.Car _Car;
        partial void OnCarChanging(global::Example.Tests.Client.Example.Data.Models.Car value);
        partial void OnCarChanged();
        /// <summary>
        /// There are no comments for Property Driver in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Example.Tests.Client.Example.Data.Models.Driver Driver
        {
            get
            {
                return this._Driver;
            }
            set
            {
                this.OnDriverChanging(value);
                this._Driver = value;
                this.OnDriverChanged();
                this.OnPropertyChanged("Driver");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Example.Tests.Client.Example.Data.Models.Driver _Driver;
        partial void OnDriverChanging(global::Example.Tests.Client.Example.Data.Models.Driver value);
        partial void OnDriverChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::Example.Tests.Client.Example.Data.Models.Race as global::Example.Tests.Client.Example.Data.Models.RaceSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::Example.Tests.Client.Example.Data.Models.RaceSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Example.Tests.Client.Example.Data.Models.Race> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::Example.Tests.Client.Example.Data.Models.RaceSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::Example.Tests.Client.Example.Data.Models.Race as global::Example.Tests.Client.Example.Data.Models.RaceSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::Example.Tests.Client.Example.Data.Models.RaceSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Example.Tests.Client.Example.Data.Models.Race> source,
            int id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::Example.Tests.Client.Example.Data.Models.RaceSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::Example.Tests.Client.Example.Data.Models.Driver as global::Example.Tests.Client.Example.Data.Models.DriverSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::Example.Tests.Client.Example.Data.Models.DriverSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Example.Tests.Client.Example.Data.Models.Driver> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::Example.Tests.Client.Example.Data.Models.DriverSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::Example.Tests.Client.Example.Data.Models.Driver as global::Example.Tests.Client.Example.Data.Models.DriverSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::Example.Tests.Client.Example.Data.Models.DriverSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Example.Tests.Client.Example.Data.Models.Driver> source,
            int id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::Example.Tests.Client.Example.Data.Models.DriverSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::Example.Tests.Client.Example.Data.Models.Car as global::Example.Tests.Client.Example.Data.Models.CarSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::Example.Tests.Client.Example.Data.Models.CarSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Example.Tests.Client.Example.Data.Models.Car> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::Example.Tests.Client.Example.Data.Models.CarSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::Example.Tests.Client.Example.Data.Models.Car as global::Example.Tests.Client.Example.Data.Models.CarSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::Example.Tests.Client.Example.Data.Models.CarSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Example.Tests.Client.Example.Data.Models.Car> source,
            int id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::Example.Tests.Client.Example.Data.Models.CarSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::Example.Tests.Client.Example.Data.Models.RaceResult as global::Example.Tests.Client.Example.Data.Models.RaceResultSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::Example.Tests.Client.Example.Data.Models.RaceResultSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Example.Tests.Client.Example.Data.Models.RaceResult> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::Example.Tests.Client.Example.Data.Models.RaceResultSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::Example.Tests.Client.Example.Data.Models.RaceResult as global::Example.Tests.Client.Example.Data.Models.RaceResultSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::Example.Tests.Client.Example.Data.Models.RaceResultSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Example.Tests.Client.Example.Data.Models.RaceResult> source,
            int id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::Example.Tests.Client.Example.Data.Models.RaceResultSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
    }
}
namespace Example.Tests.Client.Example
{
    /// <summary>
    /// There are no comments for ExampleContainer in the schema.
    /// </summary>
    public partial class ExampleContainer : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new ExampleContainer object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public ExampleContainer(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "Example.Data.Models", "Example.Tests.Client.Example.Data.Models");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Example", "Example.Tests.Client.Example");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("Example.Tests.Client.Example.Data.Models", global::System.StringComparison.Ordinal))
            {
                return string.Concat("Example.Data.Models.", clientType.Name);
            }
            if (clientType.Namespace.Equals("Example.Tests.Client.Example", global::System.StringComparison.Ordinal))
            {
                return string.Concat("Example.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Races in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::Example.Tests.Client.Example.Data.Models.Race> Races
        {
            get
            {
                if ((this._Races == null))
                {
                    this._Races = base.CreateQuery<global::Example.Tests.Client.Example.Data.Models.Race>("Races");
                }
                return this._Races;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Example.Tests.Client.Example.Data.Models.Race> _Races;
        /// <summary>
        /// There are no comments for Drivers in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::Example.Tests.Client.Example.Data.Models.Driver> Drivers
        {
            get
            {
                if ((this._Drivers == null))
                {
                    this._Drivers = base.CreateQuery<global::Example.Tests.Client.Example.Data.Models.Driver>("Drivers");
                }
                return this._Drivers;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Example.Tests.Client.Example.Data.Models.Driver> _Drivers;
        /// <summary>
        /// There are no comments for Cars in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::Example.Tests.Client.Example.Data.Models.Car> Cars
        {
            get
            {
                if ((this._Cars == null))
                {
                    this._Cars = base.CreateQuery<global::Example.Tests.Client.Example.Data.Models.Car>("Cars");
                }
                return this._Cars;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Example.Tests.Client.Example.Data.Models.Car> _Cars;
        /// <summary>
        /// There are no comments for RaceResults in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::Example.Tests.Client.Example.Data.Models.RaceResult> RaceResults
        {
            get
            {
                if ((this._RaceResults == null))
                {
                    this._RaceResults = base.CreateQuery<global::Example.Tests.Client.Example.Data.Models.RaceResult>("RaceResults");
                }
                return this._RaceResults;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Example.Tests.Client.Example.Data.Models.RaceResult> _RaceResults;
        /// <summary>
        /// There are no comments for Races in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToRaces(global::Example.Tests.Client.Example.Data.Models.Race race)
        {
            base.AddObject("Races", race);
        }
        /// <summary>
        /// There are no comments for Drivers in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToDrivers(global::Example.Tests.Client.Example.Data.Models.Driver driver)
        {
            base.AddObject("Drivers", driver);
        }
        /// <summary>
        /// There are no comments for Cars in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToCars(global::Example.Tests.Client.Example.Data.Models.Car car)
        {
            base.AddObject("Cars", car);
        }
        /// <summary>
        /// There are no comments for RaceResults in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToRaceResults(global::Example.Tests.Client.Example.Data.Models.RaceResult raceResult)
        {
            base.AddObject("RaceResults", raceResult);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private const string Edmx = @"<edmx:Edmx Version=""4.0"" xmlns:edmx=""http://docs.oasis-open.org/odata/ns/edmx"">
  <edmx:DataServices>
    <Schema Namespace=""Example.Data.Models"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityType Name=""Race"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Id"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Name"" Type=""Edm.String"" />
        <Property Name=""Laps"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""StartDateTime"" Type=""Edm.DateTimeOffset"" Nullable=""false"" />
      </EntityType>
      <EntityType Name=""Driver"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Id"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Name"" Type=""Edm.String"" />
        <NavigationProperty Name=""Cars"" Type=""Collection(Example.Data.Models.Car)"" />
      </EntityType>
      <EntityType Name=""Car"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Id"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Name"" Type=""Edm.String"" />
        <Property Name=""Year"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Make"" Type=""Edm.String"" />
        <Property Name=""Model"" Type=""Edm.String"" />
        <NavigationProperty Name=""Owner"" Type=""Example.Data.Models.Driver"" />
      </EntityType>
      <EntityType Name=""RaceResult"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Id"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""FinishTimeSpan"" Type=""Edm.Duration"" />
        <Property Name=""DidFinish"" Type=""Edm.Boolean"" Nullable=""false"" />
        <Property Name=""DidStart"" Type=""Edm.Boolean"" Nullable=""false"" />
        <Property Name=""LapsCompleted"" Type=""Edm.Int32"" />
        <Property Name=""PitStops"" Type=""Edm.Int32"" />
        <NavigationProperty Name=""Race"" Type=""Example.Data.Models.Race"" />
        <NavigationProperty Name=""Car"" Type=""Example.Data.Models.Car"" />
        <NavigationProperty Name=""Driver"" Type=""Example.Data.Models.Driver"" />
      </EntityType>
    </Schema>
    <Schema Namespace=""Example"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityContainer Name=""ExampleContainer"">
        <EntitySet Name=""Races"" EntityType=""Example.Data.Models.Race"" />
        <EntitySet Name=""Drivers"" EntityType=""Example.Data.Models.Driver"">
          <NavigationPropertyBinding Path=""Cars"" Target=""Cars"" />
        </EntitySet>
        <EntitySet Name=""Cars"" EntityType=""Example.Data.Models.Car"">
          <NavigationPropertyBinding Path=""Owner"" Target=""Drivers"" />
        </EntitySet>
        <EntitySet Name=""RaceResults"" EntityType=""Example.Data.Models.RaceResult"">
          <NavigationPropertyBinding Path=""Race"" Target=""Races"" />
          <NavigationPropertyBinding Path=""Car"" Target=""Cars"" />
          <NavigationPropertyBinding Path=""Driver"" Target=""Drivers"" />
        </EntitySet>
      </EntityContainer>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader(Edmx);
                try
                {
                    return global::Microsoft.OData.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
}
