// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Example.Data.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddRaceClass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddRaceClass));
        
        string IMigrationMetadata.Id
        {
            get { return "201510162036039_AddRaceClass"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
